[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "antlr4-python3-runtime==4.13.2",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "manim>=0.21.0",
    "python-multipart>=0.0.32",
    "sympy>=1.14.0",
    "uvicorn>=0.52.1",
]
